# Generated by Django 4.1.7 on 2023-03-12 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="genre",
            name="books",
        ),
        migrations.AddField(
            model_name="genre",
            name="rating",
            field=models.DecimalField(decimal_places=2, default=5, max_digits=5),
        ),
    ]
