# Generated by Django 4.1.7 on 2023-03-12 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_remove_genre_books_genre_rating"),
    ]

    operations = [
        migrations.RenameField(
            model_name="library",
            old_name="books",
            new_name="capacity",
        ),
    ]
