# Generated by Django 4.1.7 on 2023-03-21 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_book_genre_alter_book_library"),
    ]

    operations = [
        migrations.CreateModel(
            name="Borrowed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("days_borrowed", models.IntegerField()),
                ("extra_days_borrowed", models.IntegerField()),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.book"
                    ),
                ),
                (
                    "library",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.library"
                    ),
                ),
            ],
        ),
    ]
