# Generated by Django 4.1.7 on 2023-03-26 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_borrowed"),
    ]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("street", models.CharField(max_length=100)),
                ("street_number", models.IntegerField()),
                ("city", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Reader",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name="borrowed",
            old_name="extra_days_borrowed",
            new_name="extra_days",
        ),
        migrations.AlterField(
            model_name="book",
            name="genre",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.PROTECT, to="api.genre"
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="library",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.PROTECT, to="api.library"
            ),
        ),
        migrations.AlterField(
            model_name="borrowed",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="api.book"
            ),
        ),
        migrations.AlterField(
            model_name="borrowed",
            name="library",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="api.library"
            ),
        ),
        migrations.AddField(
            model_name="borrowed",
            name="reader",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.PROTECT, to="api.reader"
            ),
        ),
        migrations.AlterField(
            model_name="library",
            name="address",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="api.address"
            ),
        ),
    ]
