# Generated by Django 4.1.7 on 2023-03-04 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="isbn",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="book",
            name="pages",
            field=models.IntegerField(),
        ),
    ]
