# Generated by Django 4.1.7 on 2023-03-12 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_genre_library_book_library_alter_book_genre"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="library",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.PROTECT, to="api.library"
            ),
        ),
    ]
