# Generated by Django 4.1.7 on 2023-04-02 09:15

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_rename_descripiton_genre_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="pages",
            field=models.IntegerField(validators=[api.models.PageValidator]),
        ),
    ]
