# Generated by Django 4.1.7 on 2023-03-26 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="library",
            name="address",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.DO_NOTHING, to="api.address"
            ),
        ),
    ]
