# Generated by Django 4.1.7 on 2023-03-26 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_library_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrowed",
            name="reader",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="api.reader"
            ),
        ),
    ]
