# Generated by Django 4.1.7 on 2023-03-26 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_borrowed_book_alter_borrowed_library_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="borrowed",
            name="library",
        ),
    ]
