# Generated by Django 4.1.7 on 2023-03-26 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_remove_borrowed_library"),
    ]

    operations = [
        migrations.RenameField(
            model_name="genre",
            old_name="descripiton",
            new_name="description",
        ),
    ]
