# Generated by Django 4.1.7 on 2023-04-02 09:18

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_alter_book_pages"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="author",
            field=models.CharField(
                max_length=100, validators=[api.models.AuthorValidator]
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="title",
            field=models.CharField(
                max_length=100, validators=[api.models.TitleValidator]
            ),
        ),
    ]
